trainer:
  default_root_dir: null
  default_hdfs_dir: hdfs://haruna/home/byte_ecom_govern/user/yangzheming/chinese/common_model/trails/ccr_v2_multi_cls/model_outputs5
  logger: true
  log_every_n_steps: 50
  benchmark: false
  enable_speedmonitor: true
  enable_versions: false
  detect_anomaly: false
  deterministic: false
  accelerator: gpu
  accelerator_kwargs: {}
  precision: fp16
  max_epochs: 6
  max_steps: -1
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  sync_batchnorm: false
  sync_fit_metrics: null
  val_check_interval:
  - 10000
  - 1.0
  accumulate_grad_batches: null
  gradient_clip_val: null
  seed: null
  summarize_model_depth: 2
  resume_ckpt_path: auto
  callbacks: null
  enable_checkpoint: true
  checkpoint_monitor: total_ccr_micro_f1
  checkpoint_mode: max
  dataloader_timeout: -1
  dataloader_retry_limit: 100
  dataloader_retry_persistent_limit: 5
  find_unused_parameters: true
  project_name: null
  enable_trace: false
model:
  learning_rate: 0.0002
  weight_decay: 0.1
  warmup_ratio: 0.0
  pretrained_model_dir: hdfs://haruna/home/byte_ecom_govern/user/yangzheming/asr_model/zh_deberta_base_l6_emd_20210720
  local_pretrained_model_dir_prefix: /opt/tiger/yangzheming/ckpt/
  classification_task_enable: true
  star_cls_class_num: 5
  sce_loss_enable: true
  cat_max_pool_enable: true
  ccr_label_map_file: hdfs://haruna/home/byte_ecom_govern/user/yangzheming/chinese/common_model/trails/ccr_v2_multi_cls/config/ccr_voc_fourth_label_map.json
  multi_label_threshold: 0.5
  partial_load_from_checkpoints_path: hdfs://haruna/home/byte_ecom_govern/user/yangzheming/chinese/common_model/trails/ccr_v3_live_0.3b_mlm/model_outputs2/checkpoints/epoch=4-step=350000-val_loss=2.096.ckpt
  ccr_loss_weight: 1000
data:
  train_batch_size: 64
  val_batch_size: 64
  train_paths: hdfs://haruna/home/byte_ecom_govern/user/yangzheming/chinese/common_model/trails/ccr_v2_multi_cls/traindata/part*
  val_paths: hdfs://haruna/home/byte_ecom_govern/user/yangzheming/chinese/common_model/trails/ccr_v2_multi_cls/validdata/part*
  data_size: 260558329
  val_step: 0
  classification_task_enable: true
  text_field: text
  text_label_field: fourth_category
  logistics_star_label_field: rank_logistic
  product_star_label_field: rank_product
  shop_star_label_field: rank_shop
  num_workers: 2
  pretrained_model_dir: hdfs://haruna/home/byte_ecom_govern/user/yangzheming/asr_model/zh_deberta_base_l6_emd_20210720
  local_pretrained_model_dir_prefix: /opt/tiger/yangzheming/ckpt/
  cutter_enable: true
  cutter_resource_dir: hdfs://haruna/home/byte_ecom_govern/user/yangzheming/asr_model/libcut_data_zh_20200827fix2/
  local_cutter_dir_prefix: /opt/tiger/yangzheming/cutter/
  context_length: 128
  mlm_probability: 0.1
  ccr_label_map_file: hdfs://haruna/home/byte_ecom_govern/user/yangzheming/chinese/common_model/trails/ccr_v2_multi_cls/config/ccr_voc_fourth_label_map.json
log_level: INFO
