trainer:
  default_root_dir: null
  default_hdfs_dir: hdfs://harunava/home/byte_magellan_va/user/wangxian/projects/tts_all_cat_1013/cruise_raw_prop_from_trans_5e-6
  logger: true
  log_every_n_steps: 10
  benchmark: false
  enable_speedmonitor: true
  enable_versions: true
  detect_anomaly: false
  deterministic: false
  accelerator: gpu
  accelerator_kwargs: {}
  precision: fp16
  max_epochs: 2
  max_steps: -1
  limit_train_batches: null
  limit_val_batches: 2
  limit_test_batches: null
  sync_batchnorm: false
  sync_fit_metrics: null
  val_check_interval: [50, 1.0]
  accumulate_grad_batches: null
  gradient_clip_val: 1.0
  seed: 42
  summarize_model_depth: 3
  resume_ckpt_path: null
  callbacks: null
  enable_checkpoint: true
  checkpoint_monitor: step
  checkpoint_mode: max
  dataloader_timeout: -1
  dataloader_retry_limit: 100
  dataloader_retry_persistent_limit: 5
  find_unused_parameters: true
  project_name: null
  experiment_name: null
  enable_trace: false
  reload_dataloaders_every_n_epochs: -1
model:
  config_backbone: examples/framealbert_classification/config/config_backbone.yaml
  config_fusion: examples/framealbert_classification/config/config_fusion.yaml
  config_optim: examples/framealbert_classification/config/config_optim.yaml
  # config_backbone: config/config_backbone.yaml
  # config_fusion: config/config_fusion.yaml
  # config_optim: config/config_optim.yaml
  load_pretrained: hdfs://harunava/home/byte_magellan_va/user/wangxian/projects/tts_all_cat_1013/0108_allcat_trans_visionlowlr/model_state_epoch_38000.th
  low_lr_prefix: [ ]
  prefix_changes:
    - backbone.vision.->falbert.visual.
    - backbone.->falbert.
data:
  train_files: hdfs://harunava/home/byte_magellan_va/user/wangxian/datasets/TTS_KG/hr_train_jsonl,hdfs://harunava/home/byte_magellan_va/user/wangxian/datasets/TTS_KG/tmpmix_train_jsonl
  train_size: 1570000
  val_files: hdfs://harunava/home/byte_magellan_va/user/wangxian/datasets/TTS_KG_TEST/high_risk_1013_slices
  val_size: 16000
  train_batch_size: 64
  val_batch_size: 32
  num_workers: 4
  text_len: 128
  frame_len: 1
  exp: cruise_raw_prop_from_trans_5e-6
log_level: INFO
