model_name: fashion_deberta_asr
model_type: deberta
vocab_size: 145608
dim: 768
dim_ff: 3072
dim_shrink: 0
n_segments: 2
max_len: 512
n_heads: 16
n_layers: 3
embedding_dim: 256
act: "gelu"
layer_norm_eps: 1e-6
pool: true
p_drop_hidden: 0.1
p_drop_attn: 0.1
embedding_dropout: 0.1
padding_index: 0
attention_clamp_inf: false
ignore_index: -100
initializer_range: 0.02
calc_mlm_accuracy: true
omit_other_output: true
layernorm_fp16: true
max_relative_positions: 512
abs_pos_embedding: true
tie_embedding: true
use_emd: false
num_emd_groups: 1
emd_group_repeat: 1
layernorm_type: "default"
head_layernorm_type: "default"
extra_da_transformer_config:
  pos_att_type: "c2p|p2c"
  layernorm_fp16: true
  mha_acts_unite_d01: false
  omit_other_attn_output: true
