trainer:
  default_root_dir: /opt/tiger/
  default_hdfs_dir: hdfs://haruna/user/tianke/train_model
  logger: true
  log_every_n_steps: 50
  benchmark: false
  enable_speedmonitor: true
  enable_versions: true
  detect_anomaly: false
  deterministic: false
  accelerator: gpu
  accelerator_kwargs: {}
  precision: 32
  max_epochs: 3
  max_steps: -1
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  sync_batchnorm: false
  sync_fit_metrics: null
  val_check_interval:
  - 2000
  - 1.0
  accumulate_grad_batches: null
  gradient_clip_val: null
  seed: null
  summarize_model_depth: 2
  resume_ckpt_path: null
  callbacks: null
  enable_checkpoint: true
  checkpoint_monitor: loss
  checkpoint_mode: min
  dataloader_timeout: -1
  dataloader_retry_limit: 100
  dataloader_retry_persistent_limit: 5
  find_unused_parameters: true
  project_name: null
  enable_trace: false
model:
  max_seq_len: 512
  learning_rate: 2.0e-05
  betas: [0.9, 0.999]
  eps: 1.0e-08
  weight_decay: 0.1
  pretrained_model_dir: hdfs://haruna/user/tianke/pretrain_models/ddp_subword_bs8x8_1696w
  local_dir_prefix: /opt/tiger/
data:
  train_batch_size: 16
  val_batch_size: 32
  train_paths: hdfs://haruna/user/tianke/data/model_train_data/cruise_data/1_0/train
  val_paths: hdfs://haruna/user/tianke/data/model_train_data/cruise_data/1_0/predict
  data_size: 1200000
  val_data_size: 10000
  val_step: 100
  text_label_field: label
  text_field: text
  num_workers: 1
  pretrained_model_dir: hdfs://haruna/user/tianke/pretrain_models/ddp_subword_bs8x8_1696w
  local_dir_prefix: /opt/tiger/
  cutter_resource_dir: hdfs://haruna/user/tianke/tools/libcut_data_zh_20200827fix2
  max_sen_len: 512
log_level: INFO
