name: Test
trigger:
  change:
    types:
    - create
    - push
jobs:
  docker_py-codestyle-check:
    name: codestyle_check (bash ci/code-format.sh -i)
    image: hub.byted.org/arnold/nlp.fex.train_image_arnold:c833e6da45b6a2a3285a678e457fd9e5
    working-directory: fex
    steps:
    - name: Add Data CI Environments
      uses: actions/adapt-to-data-ci
    - name: Install autopep8
      commands:
        - pip3 install autopep8 --index-url=https://bytedpypi.byted.org/simple/
    - name: Python codestyle
      commands:
        - bash ci/pre-commit-hook.sh --show-only --fail-on-diff -t $GITLAB_MASTER_COMMIT_SHA -b $GITLAB_COMMIT_SHA
