# all available pretrained models
# server: server name
# url_or_path: remote url
# type: model name in `easyguard.modelzoo.modles`
# description: a short introduction to the pretrained model
# region: CN [available in China], VA [available overseas], CN/VA [available both]
# available server urls: hdfs://haruna/home/byte_ecom_govern/easyguard/models [China]
deberta_base_6l:
  server: hdfs
  type: deberta
  region: CN
fashion-deberta:
  server: hdfs
  type: deberta
  description: CCR + ASR 各1亿 MLM
  region: CN
fashion-deberta-asr:
  server: hdfs
  type: deberta
  description: 风险预测task, 6层deberta
  region: CN
fashion-deberta-asr-small:
  server: hdfs
  type: deberta
  description: 风险预测task, 3层deberta
  region: CN
fashion-deberta-ccr-order:
  server: hdfs
  type: deberta
  description: 订单型 + VOC
  region: CN
fashionxlm-base:
  server: hdfs
  type: fashionxlm
  region: CN
fashionxlm-moe-base:
  server: hdfs
  type: fashionxlm_moe
  region: CN
xlmr-base:
  server: hdfs
  type: xlmr
  region: CN
falbert-no-weights:
  server: hdfs
  type: falbert
  region: CN
  description: no pretrained weights
bert-base-uncased:
  server: hdfs
  type: bert
  region: CN
facebook/bart-large:
  type: bart
google/vit-base-patch16-224:
  type: vit
openai/clip-vit-base-patch32:
  type: clip
fashion-deberta-ner:
  server: hdfs
  type: deberta_erlangshen
  description: 短视频+直播ASR,2亿,MLM(卖点词entity mask)
  region: CN
fashion-swin-base-224-fashionvtp:
  type: fashion_swin
  server: hdfs
  region: CN
  description: fashionvtp的多模态视觉backbone
fashionbert-base:
  type: fashionbert
  server: hdfs
  region: CN


