# all model config settings, each required setting for your model can be exposed here

# the unique keys are designed for mappings
unique_keys:
  - name
  - backend
  - config_archive
  - config
  - tokenizer
  - tokenizer_fast
  - model_for_pretrained
  - image_processor
  - processor

# all models' settings
models:
  bert:
    name: BERT
    backend: hf
    config_archive: BERT_PRETRAINED_CONFIG_ARCHIVE_MAP
    configuration_bert:
      config: BertConfig
    tokenization_bert:
      tokenizer: BertTokenizer
    tokenization_bert_fast:
      tokenizer_fast: BertTokenizerFast
    modeling_bert:
      model: BertModel
      model_for_pretrained: BertForPreTraining
  bart:
    name: BART
    backend: hf
    config_archive: BART_PRETRAINED_CONFIG_ARCHIVE_MAP
    configuration_bart:
      config: BartConfig
    modeling_bart:
      model: BartModel
    tokenization_bart:
      tokenizer: BartTokenizer
    tokenization_bart_fast:
      tokenizer_fast: BartTokenizerFast
  deberta:
    name: DeBERTa
    backend: default
    configuration_deberta:
      config: DeBERTaConfig
    modeling_deberta:
      model: DebertaModel
    tokenization_deberta:
      tokenizer: DeBERTaTokenizer
  vit:
    name: Vit
    backend: hf
    configuration_vit:
      config: ViTConfig
    image_processing_vit:
      image_processor: ViTImageProcessor
    modeling_vit:
      model: ViTModel
  clip:
    name: Clip
    backend: hf
    configuration_clip:
      config: CLIPConfig
      text_config: CLIPTextConfig
      vision_config: CLIPVisionConfig
    image_processing_clip:
      image_processor: CLIPImageProcessor
    modeling_clip:
      model: CLIPModel
    processing_clip:
      processor: CLIPProcessor
    tokenization_clip:
      tokenizer: CLIPTokenizer
    
    

    
    
    