deepspeed: valley/configs/deepspeed/config_zero2.json
model_class: valley-product
model_name_or_path: /mnt/bn/yangmin-priv-fashionmm/Checkpoints/wangzhen/valley/pool_adapter_stage2_llava1.5_double_product_redirect/checkpoint-55200
data_path: /mnt/bn/yangmin-priv-fashionmm/Data/sk/continue_data/shouyi/product_continue_pretrain_basicdown_train.json
image_folder: /mnt/bn/yangmin-priv-fashionmm/Data/zhongheng/mllm_image/continut_pretrain
project_name: product_continue_pretrian
run_name: valley-pool_adapter-continue_pretrain-down-v1-2-lora
# english or chinese, default is english
language: chinese
vision_tower: /mnt/bn/yangmin-priv-fashionmm/pretrained/chinese-clip-vit-large-patch14
version: "v0"
prompt_version: "conv_prd_cp"
only_mask_system: False
mm_vision_select_feature: 'cls_patch'
mm_vision_select_layer: -2
mm_use_im_start_end: True
mm_use_im_patch_token: False
mm_projector_type: pool_adapter
pool_out_size: 8
max_img_num: 8
tune_mm_mlp_adapter: True
freeze_backbone: True
group_by_modality_length: True
bf16: False
fp16: True
lora_enable: True
output_dir: /mnt/bn/yangmin-priv-fashionmm/Data/sk/checkpoints/valley-chinese-7b-lora-product-continue-pretrain-basicdown-pool-v1-2-5epoch
num_train_epochs: 5
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 1
evaluation_strategy: "no"
save_strategy: "no"
lora_save_strategy: "steps"
save_steps: 1000
learning_rate: 0.0001
weight_decay: 0.
warmup_ratio: 0.00
lr_scheduler_type: cosine
logging_steps: 1
tf32: False
model_max_length: 2048
gradient_checkpointing: True
dataloader_num_workers: 4
lazy_preprocess: True
report_to: wandb