trainer:
  default_root_dir: null
  default_hdfs_dir: hdfs://harunasg/home/byte_magellan_govern/users/jiangjunjun.happy/xlmr14
  logger: true
  log_every_n_steps: 50
  benchmark: false
  enable_speedmonitor: true
  enable_versions: true
  detect_anomaly: false
  deterministic: false
  accelerator: gpu
  accelerator_kwargs: {}
  precision: fp16
  max_epochs: 1
  max_steps: -1
  limit_train_batches: null
  limit_val_batches: 100
  limit_test_batches: null
  sync_batchnorm: true
  sync_fit_metrics: null
  val_check_interval: 1.0
  accumulate_grad_batches: null
  gradient_clip_val: 2.0
  seed: null
  summarize_model_depth: 2
  resume_ckpt_path: null
  callbacks: null
  enable_checkpoint: true
  checkpoint_monitor: loss
  checkpoint_mode: min
  dataloader_timeout: -1
  dataloader_retry_limit: 100
  dataloader_retry_persistent_limit: 5
  find_unused_parameters: true
  project_name: null
  enable_trace: false
model:
  pretrained_model_name_or_path: fashionxlm-mdeberta-v3-base
  cl_enable: false
  cl_temp: 0.05
  cl_weight: 1.0
  ntx_enable: false
  classification_task_enable: false
  classification_task_head: 1422
  hidden_size: 768
  load_pretrain: hdfs://harunava/home/byte_magellan_va/user/jiangjunjun.happy/xlmr16/model_state_epoch_400000.th
  all_gather_limit: -1
  warmup_ratio: 0.1
  weight_decay: 0.05
  base_lr: 0.0005
  warmup_lr: 5.0e-07
  min_lr: 5.0e-06
  lr_scheduler: cosine
  lr_scheduler_decay_ratio: 0.8
  lr_scheduler_decay_rate: 0.1
  optimizer: adamw
  optimizer_eps: 1.0e-08
  optimizer_betas: [0.9, 0.999]
  momentum: 0.9
data:
  train_batch_size: 16
  val_batch_size: 16
  paths: hdfs://harunava/home/byte_magellan_va/user/jiangjunjun.happy/tiktok_text_category
  data_size: 200000000
  val_step: 500
  num_workers: 1
  tokenizer: microsoft/mdeberta-v3-base
  x_key: text
  y_key: label
  region_key: region
  pre_tokenize: false
  mlm_probability: 0.15
  cl_enable: false
  cla_task_enable: false
  category_key: category
  max_len: 256
log_level: INFO
