CONFIG_VERSION: 2

BASE:
- hdfs://haruna/home/byte_search_nlp_lq/multimodal/confighub/accelerator.yaml
- hdfs://haruna/home/byte_search_nlp_lq/multimodal/confighub/train_basic.yaml
- hdfs://haruna/home/byte_search_nlp_lq/multimodal/modelhub/videoclip_resnet_20211012/videoclip_resnet.yaml

# Trainer 所需配置，训练必备。因此用大写。
TRAINER:
  TRAIN_BATCH_SIZE: 64
  VAL_BATCH_SIZE: 32
  CHECKPOINT_FREQUENT: 10000 # 多少步保存一次ckpt
  END_EPOCH: 2
  TRAIN_DATASET_SIZE: 70119022
  VAL_DATASET_SIZE: 50000
  VAL_FREQUENT: 5000
  VAL_STEPS: 20

train:
  gpuwise_nce: true
  init_tau: 0.07
  tau_clamp: 4.6051
  freeze_prefix: []
  optim: AdamW
  lr: 4.0e-5
  wd: 0.01
  lr_schedule: cosine
  num_workers: 16
  warmup_factor: 0.2

network:
  visual_type: RN50
  project_mode: "default"
  vocab_file: hdfs://haruna/home/byte_search_nlp_lq/user/huangwenguan/modelhub/albert_6l_zh_mix_oldcut_20200921/archer/zh_old_cut_145607.vocab
  partial_pretrain:
  - hdfs://haruna/home/byte_search_nlp_lq/multimodal/modelhub/videoclip_resnet_20211012/model.th
  partial_pretrain_prefix_changes: []

dataset:
  train_path: hdfs://haruna/home/byte_search_nlp_lq/multimodal/data/video/ctr_pos
  val_path: hdfs://haruna/home/byte_search_nlp_lq/multimodal/data/video/ctr_pos # kv set
  max_len: 32
  max_frame_len: 8
  add_title: false # 训练时，视频端是否假如标题，不加就是一个跨模态；加就是多模态

val:
  num_workers: 2
